#                          $$$$$$$$                          
#                  ./$$$$$$$$$$$$$$$$$$$$$,                  
#              $$$$$$$$$$$/       \$$$$$$$$$$$$              
#           $$$$$$$$$$$$,           ,$$$$$$$$$$$$           
#         $$$$$$$$$$$$$,              ,$$$$$$$$$$$$$         
#       $$$$$$$$$$$$$$$               ,$$$$$$$$$$$$$$$       
#      $$$$$$$$$$$$$$$,              ,$$$$$$$$$$$$$$$$$,     
#    .$$$$$$$$$$$$$$,              .$$$$$$$$$$$$$$$$$$$$,    
#    $$$$$$$,               $$$$$$$$$$$$$$$$     .$$$$$$$.   
#   $$$$$.               $$$$$$$$$$$$$$$,            $$$$$   
#   $$$$               .$$$$$$$$$$$$$$$               $$$$   
#   $$$$               /$$$$$$$$$$$$$$$               ,$$$   
#   $$$$                $$$$$$$$$$$$$$.               $$$$   
#   $$$$$$               ,$$$$$$$$$$$               ,$$$$/   
#    $$$$$$$$$$,.             ..             .,$$$$$$$$$$    
#     $$$$$$$$$$$$$$$                    $$$$$$$$$$$$$$$.    
#      $$$$$$$$$$$$$$$$                $$$$$$$$$$$$$$$$      
#       .$$$$$$$$$$$$$$                $$$$$$$$$$$$$$$       
#         ,$$$$$$$$$$$$$               $$$$$$$$$$$$$         
#            $$$$$$$$$$$$            ,$$$$$$$$$$$.           
#               $$$$$$$$$$$$      $$$$$$$$$$$/               
#                    $$$$$$$$$$$$$$$$$$$$.
#                          $$$$$$$$
#
#   Created By: Five Talent Software

service: SSITH-FETT-AWSHelperService

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'develop'}
  region: ${opt:region, 'us-west-2'}
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
        - "ec2:*"
      Resource: '*'

package:
  exclude:
    - node_modules/aws-sdk/**/*

functions:
  reaper:
    handler: src/f1CleanupService.handler
    timeout: 60
    events: 
      - eventBridge:
          schedule: rate(60 minutes)
          enabled: true
